version: '{build}'

clone_folder: c:\projects\open62541
clone_depth: 20

# Avoid building branch if it is part of a PR and built anyways
skip_branch_with_pr: true

environment:
    global:
        APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -m0=lzma -mx=9
        CYG_ARCH: x86
        CYG_ROOT: C:/cygwin
        CYG_SETUP_URL: http://cygwin.com/setup-x86.exe
        CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
        CYG_CACHE: C:\cygwin\var\cache\setup
        CYG_BASH: C:/cygwin/bin/bash
        CHOCO_CACHE: C:/choco_cache
      
    matrix:
#        - CC_NAME: MinGW Makefiles
#          CC_SHORTNAME: mingw
#          MAKE: mingw32-make -j
#          FORCE_CXX: OFF
#          OUT_DIR_LIB: bin
#          OUT_DIR_EXAMPLES: bin\examples
#        - CC_NAME: Visual Studio 9 2008
#          CC_SHORTNAME: vs2008
#          # Do not build in parallel, project dependencies are not solved correctly and thus appveyor may randomly fail
#          MAKE: msbuild /m:1 /p:BuildInParallel=false /p:ContinueOnError=false /p:StopOnFirstFailure=true open62541.sln
#          FORCE_CXX: ON
#          OUT_DIR_LIB: bin\Debug
#          OUT_DIR_EXAMPLES: bin\examples\Debug
#        - CC_NAME: Visual Studio 12 2013
#          CC_SHORTNAME: vs2013
#          # Do not build in parallel, project dependencies are not solved correctly and thus appveyor may randomly fail
#          MAKE: msbuild /m:1 /p:BuildInParallel=false /p:ContinueOnError=false /p:StopOnFirstFailure=true open62541.sln
#          FORCE_CXX: OFF
#          OUT_DIR_LIB: bin\Debug
#          OUT_DIR_EXAMPLES: bin\examples\Debug
        - CC_NAME: Visual Studio 14 2015
          CC_SHORTNAME: vs2015
          # Do not build in parallel, project dependencies are not solved correctly and thus appveyor may randomly fail
          MAKE: msbuild /m:1 /p:BuildInParallel=false /p:ContinueOnError=false /p:StopOnFirstFailure=true open62541.sln
          FORCE_CXX: OFF
          OUT_DIR_LIB: bin\Debug
          OUT_DIR_EXAMPLES: bin\examples\Debug

cache:
  - C:\ProgramData\chocolatey\bin -> tools/appveyor/install.ps1
  - C:\ProgramData\chocolatey\lib -> tools/appveyor/install.ps1
#  - 'c:\miktex'

init:
  - git config --global core.autocrlf input # Attempt to ensure we don't try to convert line endings to Win32 CRLF as this will cause build to fail

install:
- ps: '& "./tools/appveyor/install.ps1"'

before_build:
- ps: '& "./tools/appveyor/before_build.ps1"'

build_script:
- ps: '& "./tools/appveyor/build.ps1"'

after_build:
  - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\open62541-%CC_SHORTNAME%-static.zip
  - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\open62541-%CC_SHORTNAME%-dynamic.zip
